pipeline {
    agent { label 'jdk-17' }
    triggers {
        pollSCM( '5 * * * *' )
    }
    tools {
        jdk 'jdk-17'
        maven 'maven'
    }
    stages {
        stage( 'vcs' ) {
            steps {
                git url: 'https://github.com/spring-projects/spring-petclinic.git',
                    branch: 'main'
            }
        }
        stage( 'build' ) {
            steps {
                sh 'java -version'
                sh 'mvn package'
            }
        }
        stage( 'artifact' ) {
            steps {
                archiveArtifacts onlyIfSuccessful: true,
                artifacts: '**/target/springpetclinic*.jar'
                junit testResults: '**/surefire-reports/TEST-*.xml'
            }
        }
    }
}