pipeline {
    agent { label 'jdk-17' }
    triggers { 
        pollSCM('5 * * * *') }
    parameters {
        choice( name: 'spc', choices: ['mvn install', 'mvn package', 'mvn clean'], description: 'spc package')
    }
    tools {
        maven 'maven'
        jdk 'jdk-17'
    }
    stages {
        stage('spc git') {
            steps {
                git url: 'https://github.com/spring-projects/spring-petclinic.git',
                    branch: 'main'
            }
        }
        stage('spc package') {
            steps {
                sh 'java -version'
                sh 'mvn package'
            }
        }
        stage('spc artifact') {
            steps {
            archiveArtifacts artifacts: '**/target/springpetclinic-jar', onlyIfSuccessful: true
            junit testResults: '**/surefire-reports/TEST-*.xml'
            }
        }
    }
}