pipeline {
    agent { label 'jdk-8' }
    triggers {
        pollSCM( '5 * * * *' )
    }
    parameters {
        choice(name: 'jdk-8', choices: [ 'mvn install', 'mvn package', 'mvn clean' ], description: 'pick one' )
    }
    tools {
        jdk 'jdk-8'
    }
    stages {
        stage('vcs') {
            steps { 
                git url: 'https://github.com/wakaleo/game-of-life.git'
                }
        }
        stage('packages') {
            steps {
                rtMavenDeployer (
                    id: "maven-deployer",
                    serverId: "JFROG",
                    releaseRepo: nadeem-jfrog-libs-release,
                    snapshotRepo: nadeem-jfrog-libs-snapshot,
                )
                rtMavenRun (
                    tool: 'Maven 3.3.9',
                    pom: 'pom.xml',
                    goals: 'clean install',
                    deployerId: "maven-deployer",
                )
                rtPublishBuildInfo (
                    serverId: "JFROG"
                )
            }
        }
        stage('reporting') {
            steps {
                junit testResults: '**/target/surefire-reports/TEST-*.xml'
            }
        }
        
    }
}
