pipeline {
    agent { label 'jdk-8' }
    triggers {
        pollSCM( '5 * * * *' )
    }
    parameters {
        choice(name: 'jdk-8', choices: [ 'mvn install', 'mvn package', 'mvn clean' ], description: 'pick one' )
    }
    tools {
        jdk 'javamaven6'
        maven 'maven-6'
    }
    stages {
        stage('vcs') {
            steps { 
                git url: 'https://github.com/wakaleo/game-of-life.git',
                    branch: 'master'
            }
        }
        stage('packages') {
            steps {
                sh 'java -version'
                sh 'mvn --version'
                sh 'mvn package'
            }
        }
        stage('artifact') {
            steps {
                archiveArtifacts onlyIfSuccessful: true,
                artifacts: '**/target/gameoflife.war'
                junit testResults: '**/surefire-reports/TEST-*.xml'
            }
        }
    }
}
