pipeline {
    agent { label 'jdk-8' }
    triggers {
        pollSCM( '5 * * * *' )
    }
    parameters {
        choice(name: 'jdk-8', choices: [ 'mvn install', 'mvn package', 'mvn clean' ], description: 'pick one' )
    }
    tools {
        jdk 'jdk-8'
        maven 'maven-6'
    }
    stages {
        stage('vcs') {
            steps { 
                git url: 'https://github.com/wakaleo/game-of-life.git'
                }
        }
        stage('packages') {
            steps {
                sh ' export PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin" '
                sh 'java -version'
                sh 'mvn --version'
                sh 'mvn package'
            }
        }
        stage('artifact') {
            steps {
                archiveArtifacts onlyIfSuccessful: true,
                artifacts: '**/target/gameoflife.war'
                junit testResults: '**/surefire-reports/TEST-*.xml'
            }
        }
    }
}
